'use strict';
let S=null,page='today',sessionId='',selectedRefs=[],quoteOffset=0,poll=null,showArchived=false;
let selectedDomain='',advisorQuery='',advisorCategory='',reading=null,readerInfo=null,readerSlug='',noteSeed=null,adoptDomain=null,recordSource=null,contextCandidates=[],contextWarnings=[],lastMessages=[],knowledgeQuery='';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={today:'我的今天',panorama:'人生全景',goals:'目标与计划',advisors:'顾问书房',reading:'顾问书房',notes:'想法与复盘',review:'一次成长复盘',chat:'与 Codex 协作',knowledge:'我的知识库',process:'连接与留底'};
const statuses={draft:'等待采用',proposed:'待取舍',active:'正在推进',paused:'暂缓',done:'已完成',archived:'已归档',saved:'已保存 · 待入库',indexing:'正在入库',indexed:'已入知识库',failed:'未完成 · 可重试',queued:'等待 Codex',running:'Codex 正在思考',completed:'Codex 已回复',cancelling:'正在停止',cancelled:'已停止',interrupted:'运行中断',reading:'正在阅读',read:'已读',practiced:'已实践'};
const time=s=>s?new Date(s).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
const list=x=>Array.isArray(x)?x:x?[x]:[];
const plain=x=>Array.isArray(x)?x.map(plain).join('；'):typeof x==='string'?x:x?.text||x?.title||x?.name||'';
const clip=(s,n=100)=>String(plain(s)).length>n?String(plain(s)).slice(0,n)+'…':String(plain(s));
const domains=()=>list(S?.plan?.domains),domain=id=>domains().find(x=>x.id===id),advisor=n=>S.advisors.find(a=>a.name===n||a.slug===n),nameOf=a=>a?.name||a?.slug||'';
const safeURL=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const link=(s,label)=>safeURL(s)?`<a href="${esc(safeURL(s))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:esc(label);
const btn=(label,action,cls='')=>`<button class="${cls}" data-action="${esc(action)}">${label}</button>`;
const tag=(s,cls='')=>`<span class="tag ${cls}">${esc(s)}</span>`;
const sourceTitle=id=>{const r=S?.plan?.source_register;return (Array.isArray(r)?r.find(x=>x.id===id):r?.[id])?.title||id||'本地资料'};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4800)}
async function api(path,d,renewed=false){let r;try{r=await fetch(path,{method:d!==undefined?'POST':'GET',headers:d!==undefined?{'Content-Type':'application/json','X-Desk-Token':S?.token||''}:{},body:d!==undefined?JSON.stringify(d):undefined})}catch{throw Error('本地服务连接中断，输入已保留。恢复服务后请重试。')}let x;try{x=await r.json()}catch{throw Error('服务没有返回可读结果，请保留输入后重试。')}if(!r.ok){if(r.status===403&&d!==undefined&&!renewed&&x.error==='会话已更新，请刷新页面'){const fresh=await api('/api/state');S.token=fresh.token;return api(path,d,true)}throw Error(x.error||'操作没有完成，请重试')}return x}
async function refresh(render=true){S=await api('/api/state');for(const k of ['goals','notes','learning','sessions','jobs','advisors'])S[k]||=[];$('#topstatus').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});if(render)await draw()}
function open(html,wide=false){$('#modal').classList.toggle('wide',wide);$('#modalbody').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function close(){ $('#modal').close() }
function title(h,sub='',action='',eyebrow=''){return `<div class="pagetitle"><div>${eyebrow?`<div class="eyebrow">${esc(eyebrow)}</div>`:''}<h1>${esc(h)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div>${action}</div>`}
function section(h,action='',eyebrow=''){return `<div class="sectionhead"><div>${eyebrow?`<div class="eyebrow">${esc(eyebrow)}</div>`:''}<h2>${esc(h)}</h2></div>${action}</div>`}
function inlineMD(t){return esc(t).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,(_,label,url)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`)}
function markdown(text){let code=false,buf=[],out=[],ul=false;const endList=()=>{if(ul){out.push('</ul>');ul=false}};for(const line of String(text||'').split('\n')){if(/^\s*```/.test(line)){endList();if(code){out.push('<pre>'+esc(buf.join('\n'))+'</pre>');buf=[]}code=!code;continue}if(code){buf.push(line);continue}if(/^\s*[-*+]\s+|^\s*\d+[.)]\s+/.test(line)){if(!ul){out.push('<ul>');ul=true}out.push('<li>'+inlineMD(line.replace(/^\s*(?:[-*+]|\d+[.)])\s+/,''))+'</li>');continue}endList();const h=line.match(/^(#{1,6})\s+(.+)$/);if(h){const level=Math.min(h[1].length+1,4);out.push(`<h${level}>${inlineMD(h[2])}</h${level}>`)}else if(/^>\s?/.test(line))out.push('<blockquote>'+inlineMD(line.replace(/^>\s?/,''))+'</blockquote>');else if(/^\s*---+\s*$/.test(line))out.push('<hr>');else if(line.trim())out.push('<p>'+inlineMD(line)+'</p>')}endList();if(buf.length)out.push('<pre>'+esc(buf.join('\n'))+'</pre>');return out.join('')}
function addRef(r){if(selectedRefs.some(x=>x.id===r.id))return;if(selectedRefs.length>=4)throw Error('每轮最多带 4 份资料，请先移除一份。');selectedRefs.push({id:r.id,title:r.title})}
async function navigate(p){page=p;await draw();window.scrollTo({top:0,behavior:'instant'})}
function activeGoals(){return S.goals.filter(g=>g.status==='active')}
function pendingTasks(){return activeGoals().flatMap(g=>list(g.steps).filter(s=>!s.done).map(s=>({...s,goal:g}))).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||(a.goal.priority||2)-(b.goal.priority||2))}
function todayTasks(){return pendingTasks().filter(t=>t.due&&t.due<=S.date)}
function domainMini(d){const g=activeGoals().find(g=>g.domain_id===d.id),f=list(d.known_facts)[0];return `<button class="domain-mini" data-action="domain:${esc(d.id)}"><span class="domain-top">${esc(d.title.split(/[：:]/)[0])} <span>↗</span></span><strong>${esc(g?.title||d.plan_draft?.title||d.priority_reason)}</strong><small>${g?'正在推进':f?.date?f.date+' · 从资料整理':'从资料整理 · 待取舍'}</small></button>`}
function proposalTask(d,i=0,selectedAction=null){const a=selectedAction||list(d.actions)[0];if(!a)return '';return `<article class="task"><span class="ordinal">0${i+1}</span><div><div class="row spread"><h3>${esc(a.title)}</h3>${tag('建议 · 待取舍','warm')}</div><p>${esc(clip(plain(list(a.steps)[0])||a.completion_evidence||d.plan_draft?.approach,125))}</p><div class="row spread"><small>${esc(d.title)}</small><div class="actions">${btn('查看依据','domain:'+d.id,'linkbtn')}${btn('采用 / 调整 →','adopt:'+d.id+':'+a.id,'linkbtn')}</div></div></div></article>`}
function proposedPicks(){const preferred=list(S.plan?.current_focus_draft?.suggested_action_ids),all=domains().flatMap(d=>list(d.actions).map(a=>({d,a})));return preferred.length?preferred.map(id=>all.find(x=>x.a.id===id)).filter(Boolean):domains().map(d=>({d,a:list(d.actions)[0]})).filter(x=>x.a)}
function actualTask(t){return `<article class="task"><input aria-label="完成 ${esc(t.text)}" type="checkbox" data-step="${esc(t.goal.id)}:${esc(t.id)}"><div><h3>${esc(t.text)}</h3><p>${esc(t.criterion||t.goal.title)}</p><div class="row spread"><small>${t.due?esc(t.due)+(t.due<S.date?' · 待重新安排':''):'尚未安排日期'} · ${esc(t.goal.title)}</small>${btn('安排与结果','step:'+t.goal.id+':'+t.id,'linkbtn')}</div></div></article>`}
function weekStrip(){const today=new Date(),monday=new Date(today);monday.setDate(today.getDate()-(today.getDay()+6)%7);return `<div class="week-days">${Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return `<span class="${d.toDateString()===today.toDateString()?'today':''}">${'一二三四五六日'[i]}<b>${d.getDate()}</b></span>`}).join('')}</div>`}
function capture(){return `<div class="capture-box"><textarea id="capture" class="capture" placeholder="一个念头、今天的卡点，或刚刚想明白的事……">${esc(localStorage.getItem('growth-draft')||'')}</textarea><div class="actions"><span class="subtle">先留下原话</span><div class="row">${btn('保存','capture-save')}${btn('保存并入库','capture-index')}${btn('带去讨论 ↗','capture-chat','primary')}</div></div></div>`}
function recentChanges(){const records=[...S.notes.map(n=>({title:n.title,sub:statuses[n.index_state]||'已保存',date:n.updated_at||n.created_at,action:'note:'+n.id})),...S.learning.map(l=>({title:advisor(l.advisor)?.title||l.advisor,sub:statuses[l.status]||'学习记录',date:l.updated_at||l.read_at,action:'advisor:'+l.advisor})),...S.goals.map(g=>({title:g.title,sub:statuses[g.status],date:g.updated_at||g.created_at,action:'goal:'+g.id}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,3);return records.length?records.map(r=>`<div class="recent-item"><span class="recent-dot"></span><div>${btn(esc(r.title),r.action,'linkbtn')}<small>${esc(r.sub)} · ${time(r.date)}</small></div></div>`).join(''):'<p class="subtle">先从上方已经整理好的方向里，选一件愿意推进的事。你的取舍、学习与结果，会留在这里。</p>'}
function learningPicks(){const chosen=[];for(const d of domains()){for(const slug of list(d.advisor_slugs)){const a=advisor(slug);if(a?.installed&&!chosen.some(x=>nameOf(x.a)===slug)){chosen.push({a,d});break}}if(chosen.length===3)break}if(chosen.length<3)for(const a of S.advisors.filter(x=>x.installed)){if(chosen.some(x=>nameOf(x.a)===nameOf(a)))continue;chosen.push({a,d:null});if(chosen.length===3)break}return chosen}
function learningCard({a,d}){const l=S.learning.find(x=>x.advisor===nameOf(a));return `<article class="card learning-card"><div class="row spread">${tag(d?.title||a.category)}<small>${l?statuses[l.status]||'曾经读过':'从问题出发'}</small></div><h3>${esc(a.title)}</h3><p>${esc(d?.plan_draft?.title||a.review_note||'读一份方法，看看它能怎样回应你眼前的困惑。')}</p><div class="card-meta">${esc(d?.plan_draft?.why?clip(d.plan_draft.why,76):'先读原文，再留下自己的理解。')}</div><div class="row spread">${btn(l?'继续阅读 →':'开始阅读 →','advisor:'+nameOf(a),'linkbtn')}${d?btn('对应的方向','domain:'+d.id,'linkbtn'):''}</div></article>`}
function hasCommitments(){return S.commitments?.connected===true}
function commitmentView(compact=false){const c=S.commitments;if(!hasCommitments())return '';const items=Array.isArray(c.goal_statuses)?c.goal_statuses:Object.entries(c.goal_statuses||{}).map(([title,v])=>typeof v==='string'?{title,status:v}:{title,...v}),next=list(c.next_actions),updated=c.updated_at||c.cutoff;return `<section class="panel commitment-panel"><div class="row spread"><div><div class="eyebrow">沿用你的目标台账</div><h2>本周建议，等你取舍</h2></div>${btn('回读原台账','read:source:canonical-commitments','linkbtn')}</div><p class="subtle">${c.review_on?'下次回看 '+esc(c.review_on):''} · 建议日期不代表已经承诺</p><div class="commitment-actions">${next.map(x=>`<div class="week-item"><strong>${esc(x.deliverable||plain(x)||x.action||x.task||'近期建议')}</strong><p>${esc(x.commitment||x.status||'建议，尚未承诺')}${x.proposed_due?' · 建议 '+esc(x.proposed_due):''}</p>${x.effort?'<small>'+esc(x.effort)+'</small>':''}</div>`).join('')}</div><details class="commitment-history"><summary>已有方向与最近复盘 · ${items.length} 条历史状态</summary><p class="subtle">${esc(c.period||'')}${updated?' · 更新于 '+esc(new Date(updated).toLocaleDateString('zh-CN',{year:'numeric',month:'numeric',day:'numeric'})):''}</p>${items.map(x=>`<div class="week-item"><strong>${esc(x.title||x.goal||x.name||x.direction||'已有方向')}</strong><p>${esc(typeof x.status==='string'?x.status:plain(x.status))}${x.result?' · '+esc(x.result):''}${x.note?' · '+esc(x.note):''}</p></div>`).join('')}<p class="subtle">原台账保持只读。工作台中的采用与执行状态单独留底，不自动改写历史。</p></details></section>`}
function domainCard(d){const g=S.goals.find(g=>g.domain_id===d.id&&g.status==='active'),a=list(d.actions)[0],fact=list(d.known_facts)[0];return `<article class="card domain-card"><div class="row spread"><div class="eyebrow">${esc(d.title)}</div>${tag(g?'已采用':'从资料整理 · 待取舍',g?'good':'warm')}</div><h2>${esc(g?.title||d.plan_draft?.title||d.title)}</h2><p>${esc(d.plan_draft?.why||d.priority_reason)}</p><div class="domain-summary">${esc(clip(d.priority_reason||d.plan_draft?.approach,180))}</div><div class="source-line">${fact?esc(fact.date||'日期见原文')+' · '+esc(sourceTitle(fact.source_id)):'方案依据见详情'}${list(d.unknowns).length?' · '+list(d.unknowns).length+' 项待补充':''}</div><div class="next-action"><small>可以先做这件事</small><h3>${esc(a?.title||'整理这个方向的下一步')}</h3><p>${esc(clip(a?.completion_evidence||plain(list(a?.steps)[0]),100))}</p></div><div class="actions">${btn(g?'查看已采用目标':'采用 / 调整',g?'goal:'+g.id:'adopt:'+d.id,'primary')}${btn('依据与方案','domain:'+d.id,'linkbtn')}${btn('与顾问讨论','domain-chat:'+d.id,'linkbtn')}</div></article>`}
function sourceLinks(ids){return [...new Set(list(ids).filter(Boolean))].map(id=>btn('回读：'+esc(sourceTitle(id)),'read:source:'+String(id).replace(/^source:/,''),'linkbtn')).join('')}
function executionLinks(id){return list(S.plan?.execution_links).filter(x=>(!id||x.domain_id===id)&&safeURL(x.url)).map(x=>link(x.url,x.label||'打开原工作台')).join(' · ')}
function todayView(){
 const q=S.quote,tasks=todayTasks(),pending=pendingTasks(),unplanned=pending.filter(t=>!t.due),future=pending.filter(t=>t.due>S.date),learning=learningPicks().slice(0,1);
 const candidates=!tasks.length&&!unplanned.length?proposedPicks().slice(0,2):[];
 return `<section class="hero"><div class="hero-body"><div class="eyebrow">今日提醒 · ${esc(q?.advisor||'成长书房')}</div><blockquote class="${(q?.text||'').length>36?'long-quote':''}">${esc(q?.text||'把值得的事，往前推进一点。')}</blockquote><div class="quote-person">${esc(q?.type||'工作台寄语')} · ${esc(S.date)}</div><p class="reflection">${esc(q?.reflection||'今天，选一个能在真实生活里验证的小行动。')}</p><div class="actions">${btn('带着它开始今天 →','quote-chat','primary')}${btn('出处与原文','quote-source','linkbtn')}${btn('换个视角','quote-next','linkbtn')}</div></div><span class="scene-caption">在自己的书桌前，慢慢生长</span></section>`+
 section('把注意力放回今天',btn('安排阶段计划 →','page:goals','linkbtn'),'行动 · 当日与待重排')+
 (executionLinks('creation')?'<div class="execution-entry">'+executionLinks('creation')+'</div>':'')+
 `<div class="grid today-focus-grid"><section class="panel topline"><div class="row spread"><h2>${tasks.length?'今天与待重排的行动':'今天还没有已排定的行动'}</h2>${tag(tasks.length?tasks.length+' 项到期或待重排':'按自己的节奏','blue')}</div>${tasks.length?'<div class="task-list">'+tasks.map(actualTask).join(''):'<p class="subtle">从已经决定的事里安排一步，或先处理眼前的卡点。</p>'}${unplanned.length?`<details class="unplanned-actions"><summary>已采用，尚未排期 · ${unplanned.length} 项</summary><p class="subtle">这些是你确认过的行动，尚未指定今天完成。</p>${unplanned.slice(0,3).map(actualTask).join('')}${unplanned.length>3?btn('查看全部未排期行动','page:goals','linkbtn'):''}</details>`:''}${candidates.length?`<div class="unplanned-actions"><h3>还没决定时，可以从这里取舍</h3><small>资料中的候选步骤 · 尚未采用，也没有安排到今天</small><div class="task-list">${candidates.map((x,i)=>proposalTask(x.d,i,x.a)).join('')}</div></div>`:''}${future.length?`<p class="subtle">另有 ${future.length} 项安排在未来，保留在${btn('目标与计划','page:goals','linkbtn')}。</p>`:''}</section><section class="panel today-reading"><div class="eyebrow">今天读一点</div><h2>带着一个问题学习</h2>${learning.length?learning.map(learningCard).join(''):'<p class="subtle">先到顾问书房，选一个与你眼前问题有关的方法。</p>'}${btn('顾问书房 →','page:advisors','linkbtn')}</section></div>`+
 section('给今天留一页')+`<div class="grid"><section class="panel"><h2>今天的想法或卡点</h2>${capture()}</section><section class="panel"><div class="row spread"><h2>最近的变化</h2>${btn('全部记录','page:notes','linkbtn')}</div>${recentChanges()}</section></div>`;
}
function panoramaView(){
 const p=S.plan?.life_panorama;if(!p)return title('人生全景','把长期愿望、现实处境与当前阶段放在一起。')+`<section class="panel"><h2>长期全景资料尚未接入</h2><p>现有行动方案不等于你的人生全景。这里需要有来源的个人愿望与阶段记录，接入后才能呈现。</p>${btn('查看已有阶段计划','page:goals','linkbtn')}${btn('讨论我的长期方向','page:chat','primary')}</section>`;
 const n=p.north_star||{},m=p.mastery||{};
 return title(p.title||'人生全景',p.subtitle||'先看想要的生活，再看正在走的路。',btn('查看阶段目标 →','page:goals','linkbtn'),'愿景 · 路径 · 生活')+
 `<section class="vision-hero"><div class="eyebrow">我想要的生活</div><blockquote>${esc(n.quote||'尚未记录本人愿景原话')}</blockquote><div class="vision-caption">${esc(n.status||'材料中的愿望')}${n.date?' · '+esc(n.date):' · 原件日期见出处'}</div>${n.interpretation?'<p>'+esc(n.interpretation)+'</p>':''}<div class="vision-sources">${sourceLinks(n.source_id)}</div>${list(p.route)[0]?`<div class="vision-now"><strong>${esc(p.route[0].title)}</strong><span>${esc(p.route[0].horizon)}</span><small>${esc(p.route[0].status)}</small></div>`:''}</section>`+
 section('这些方向，共同组成我的生活','','愿景地图')+`<div class="vision-grid">${list(p.pillars).map((x,i)=>`<article class="vision-pillar"><div class="vision-number">${String(i+1).padStart(2,'0')}</div><div><h2>${esc(x.title)}</h2><p class="desired-life">${esc(x.desired_life)}</p><p>${esc(x.meaning)}</p><small>${esc(x.status||'从本人材料整理')}</small><details><summary>依据与对应方向</summary><div class="vision-sources">${sourceLinks(x.source_ids)}</div><div class="actions">${list(x.domain_ids).filter(id=>domain(id)).map(id=>btn('相关方案：'+esc(domain(id).title.split(/[：:]/)[0]),'domain:'+id,'linkbtn')).join('')}</div></details></div></article>`).join('')}</div>`+
 section('愿景很远，路径可以调整','','阶段路线')+`<div class="life-route">${list(p.route).map((x,i)=>`<article class="route-stage"><div class="route-anchor">${String(i+1).padStart(2,'0')}</div><div><span class="eyebrow">${esc(x.horizon)}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><small>${esc(x.status)}</small>${x.evidence_needed?'<div class="route-condition"><strong>需要看到什么依据</strong><p>'+esc(plain(x.evidence_needed))+'</p></div>':''}<div class="vision-sources">${sourceLinks(x.source_ids)}</div></div></article>`).join('')}</div>`+
 section(m.title||'让我伟大：让近期工作更专精','','成长方法')+`<section class="panel mastery-panel">${m.quote?'<blockquote>'+esc(m.quote)+'</blockquote>':''}${m.date?'<small class="mastery-date">'+esc(m.date)+'</small>':''}<div class="mastery-steps">${list(m.steps).map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></div>`).join('')}</div><p class="subtle">${esc(m.boundary||'近期专精指导与长程愿景相互连接，具体行动由本人取舍。')}</p><div class="actions">${btn('按这套方法，讨论当前卡点 →','panorama-discuss:mastery','primary')}${sourceLinks(m.source_id)}</div></section>`+
 section('走得远，也要过好生活','','需要守住的条件')+`<div class="life-boundaries">${list(p.boundaries).map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="vision-sources">${sourceLinks(x.source_ids)}</div></article>`).join('')}</div>`+
 (list(p.history).length?`<details class="panel panorama-history"><summary><strong>我的方向怎样走到现在</strong><span class="subtle"> 回看变化与原始依据</span></summary><div class="vision-timeline">${list(p.history).map(x=>`<article><small>${esc(x.date)}</small><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><span class="history-status">${esc(x.status)}</span><div class="vision-sources">${sourceLinks(x.source_ids)}</div></article>`).join('')}</div>${p.history_note?'<p class="subtle">'+esc(p.history_note)+'</p>':''}</details>`:p.history_note?`<aside class="panorama-history"><strong>方向的变化，也值得留下</strong><p>${esc(p.history_note)}</p></aside>`:'');
}
function planCandidate(d){const active=activeGoals().find(g=>g.domain_id===d.id);return `<details class="plan-candidate" id="candidate-${esc(d.id)}"><summary><span><small>${esc(d.title)}</small><strong>${esc(d.plan_draft?.title||d.title)}</strong></span>${tag(active?'已有执行目标':'候选 · 未采用',active?'blue':'warm')}</summary><div class="candidate-body"><p>${esc(d.plan_draft?.why||d.priority_reason)}</p><div class="candidate-criterion"><strong>怎样算做到</strong><p>${esc(d.plan_draft?.success_definition||'查看每一步的完成依据，并按自己的情况调整。')}</p></div><ol>${list(d.actions).map(a=>`<li><strong>${esc(a.title)}</strong><p>${esc(plain(a.completion_evidence))}</p></li>`).join('')}</ol><p class="subtle">回看时机：${esc(d.plan_draft?.review_trigger||'阶段结果或现实条件发生变化时')}</p><div class="actions">${btn(active?'查看执行目标':'采用 / 调整',active?'goal:'+active.id:'adopt:'+d.id,'primary')}${btn('依据与完整方案','domain:'+d.id,'linkbtn')}${executionLinks(d.id)}</div></div></details>`}
function goalsView(){
 const active=activeGoals(),drafts=S.goals.filter(g=>g.status==='draft'||g.status==='proposed'),paused=S.goals.filter(g=>g.status==='paused'),past=S.goals.filter(g=>['done','archived'].includes(g.status)),pending=pendingTasks();
 return title('把方向，变成可检验的阶段结果。','这里管理目标、步骤、排期和结果。人生愿景留在全景，今天只处理当下行动。',btn('＋ 自定一个目标','goal:new','primary'),'目标 · 周期 · 结果')+
 `<div class="plan-overview"><div><strong>${activeGoals().length}</strong><span>正在推进的目标</span></div><div><strong>${pending.filter(t=>t.due).length}</strong><span>已安排日期的行动</span></div><div><strong>${pending.filter(t=>!t.due).length}</strong><span>已采用、尚未排期</span></div></div>`+
 section('我决定推进的阶段结果',btn('回看人生全景 →','page:panorama','linkbtn'))+`<section class="panel">${active.length?active.map(goalCard).join(''):'<div class="plan-empty"><h3>还没有确认采用的阶段目标</h3><p>下方的候选方案已整理好依据、步骤与完成标准。你可以直接取舍和修改，不必从空白页填写。</p></div>'}</section>`+
 (drafts.length?section('草稿与待确认目标')+`<section class="panel"><p class="subtle">以下内容尚未采用，不计入正在推进。</p>${drafts.map(goalCard).join('')}</section>`:'')+
 (paused.length?`<details class="panel"><summary>暂缓中的目标 · ${paused.length} 项</summary><p class="subtle">保留安排与结果，恢复后再进入当日行动。</p>${paused.map(goalCard).join('')}</details>`:'')+
 section('候选方案，按需要展开','','取舍与安排')+`<section class="panel candidate-list">${domains().map(planCandidate).join('')||'<p class="subtle">尚未接入个人阶段方案，可以先记录自己的目标。</p>'}</section>`+
 (hasCommitments()?`<details class="panel plan-ledger"><summary><strong>原目标台账与本周建议</strong><span class="subtle"> 保留来源，不自动变成新承诺</span></summary>${commitmentView()}</details>`:'')+
 (past.length?`<details class="panel"><summary>已完成与归档目标 · ${past.length} 项</summary>${past.map(goalCard).join('')}</details>`:'');
}
function recordOrigin(id){return /^(message|note):[a-f0-9]+$/.test(id||'')?btn(id.startsWith('message:')?'回看原讨论':'回看原记录','read:'+id,'linkbtn'):''}
function goalCard(g){const steps=list(g.steps),done=steps.filter(s=>s.done).length;return `<article class="goal"><div class="row spread"><h3>${esc(g.title)}</h3>${tag(statuses[g.status]||g.status,g.status==='active'?'blue':'')}</div><p class="goal-why">${esc(g.why)}${g.due?' · '+esc(g.due):''}</p><div class="row spread"><small>${esc(domain(g.domain_id)?.title||g.domain||'个人目标')} · ${done} / ${steps.length} 个行动完成</small>${g.parent_id?tag('连接长期方向'):''}</div><progress class="goal-progress" value="${done}" max="${Math.max(1,steps.length)}" aria-label="${esc(g.title)}：${done} / ${steps.length} 个行动完成">${steps.length?Math.round(done/steps.length*100):0}%</progress>${steps.map(t=>`<label class="step"><input type="checkbox" aria-label="完成 ${esc(t.text)}" data-step="${esc(g.id)}:${esc(t.id)}" ${t.done?'checked':''}><span>${esc(t.text)}</span></label><div class="step-meta">${t.due?esc(t.due)+' · ':''}${esc(t.outcome||t.criterion||'')}${btn(t.outcome?'查看结果':'安排与结果','step:'+g.id+':'+t.id,'linkbtn')}${recordOrigin(t.source_id)}</div>`).join('')}<div class="actions">${btn('调整目标','goal:'+g.id,'small')}${btn('一次复盘','review:'+g.id,'small')}${btn('与顾问讨论','discuss-goal:'+g.id,'linkbtn')}${recordOrigin(g.origin_id)}</div></article>`}
async function draw(){if(!S)return;clearTimeout(poll);$('#crumb').textContent=labels[page]||labels.today;document.querySelectorAll('[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===(page==='reading'?'advisors':page==='review'?'notes':page)));const v=$('#view');v.classList.toggle('chat-view',page==='chat');
if(page==='today'){v.innerHTML=todayView();
}else if(page==='panorama'){v.innerHTML=panoramaView();
}else if(page==='goals'){v.innerHTML=goalsView();
}else if(page==='advisors'){v.innerHTML=title('顾问书房','先找当前问题，再读方法与原文。理解留给自己，运用落到真实行动。')+continuedReading()+methodSection()+`<section class="panel library-panel"><div class="panel-heading row spread"><h2>按人生问题找顾问</h2><small>${S.stats.installed} 个本机可读 · ${S.stats.advisors} 个来源入口</small></div><div class="library-content"><div class="category-tiles">${domains().map(d=>`<button class="category-tile" data-action="library-domain:${esc(d.id)}"><strong>${esc(d.title)}</strong><small>${esc(clip(d.plan_draft?.title,36))}</small></button>`).join('')}</div><div class="toolbar"><input id="advisor-search" aria-label="搜索顾问与方法" placeholder="顾问名，或你正在面对的问题……" value="${esc(advisorQuery)}"><select id="category" aria-label="领域筛选"><option value="">所有类别</option>${[...new Set(S.advisors.map(a=>a.category))].map(c=>`<option ${c===advisorCategory?'selected':''}>${esc(c)}</option>`).join('')}</select>${btn('全部','library-all','small')}</div><div id="advisor-results">${advisorTable()}</div></div></section>`;
}else if(page==='reading'){await renderReader();
}else if(page==='notes'){v.innerHTML=title('想法有地方放，成长有迹可循。','保留原话、修改历史和真实结果。需要时，再把它变成行动。',btn('做一次成长复盘','review:','primary'))+`<section class="panel">${capture()}</section>`+section(showArchived?'归档记录':'最近的想法与复盘',btn(showArchived?'返回最近':'查看归档','toggle-archive','linkbtn'))+`<section class="panel">${S.notes.filter(n=>Boolean(n.archived)===showArchived).map(noteCard).join('')||'<div class="empty">这里会保存你的想法、学习理解和复盘。也可以从一条顾问内容或 Codex 回复开始。</div>'}</section>`;
}else if(page==='review'){renderReview(v);
}else if(page==='chat'){v.innerHTML=`<div class="pagetitle chat-title"><div><h1>和 Codex 一起，把下一步想清楚。</h1><p class="subtle">AI 助理 · 按所选资料分析，重要判断请核对依据。</p></div><div class="row"><select id="session-select" aria-label="选择对话"><option value="">新对话</option>${S.sessions.map(s=>`<option value="${esc(s.id)}" ${sessionId===s.id?'selected':''}>${esc(clip(s.title,26))}</option>`).join('')}</select>${btn('＋ 新对话','new-chat','small')}</div></div><div class="chat-layout"><section class="chat-main"><div class="chat-topline"><span>${selectedDomain?esc(domain(selectedDomain)?.title)+' · ':''}本轮围绕一个具体问题</span><span>选资料 → 预览 → 讨论 → 行动</span></div><div id="messages" class="chatmessages"></div><div id="job-state"></div><div class="composer"><label for="chat-text">现在最想聊清楚什么？</label><textarea id="chat-text" placeholder="直接说出问题。右侧可以找顾问和个人资料，一起讨论。">${esc(localStorage.getItem('growth-chat-draft')||'')}</textarea><div class="actions"><small>只有预览确认的内容随本轮发送</small><div class="row">${btn('找相关资料','recommend-context','small')}${btn('预览并发送 ↑','preview','primary')}</div></div></div></section><details class="chat-context" ${window.innerWidth>760?'open':''}><summary>本轮资料与发送预览 · <span id="context-count">${selectedRefs.length}</span> 份已选</summary><div class="context-inner"><h3>本轮资料</h3><p class="subtle">先在本机查找，需要时再选入对话。</p><div class="toolbar"><input id="context-query" aria-label="搜索本轮资料" placeholder="搜一个具体问题或关键词">${btn('查找','context-search','small')}</div><div id="selected-refs">${refsHTML()}</div><label class="step"><input type="checkbox" id="include-goals">附上我正在推进的目标与行动</label><div id="context-results">${candidatesHTML()}</div><hr class="context-divider"><div id="send-preview" class="context-preview"><p class="subtle">发送前，这里会逐项列出资料正文和携带的历史。</p></div></div></details></div>`;await loadMessages();
}else if(page==='knowledge'){v.innerHTML=title('把读过和做过，变成下一次的依据。','搜索原资料、学习记录与自己的经验。先回读，再决定如何使用。')+`<div class="toolbar"><input id="knowledge-query" aria-label="搜索知识库" placeholder="例如：实践、AI 学习、职业、预算……" value="${esc(knowledgeQuery)}">${btn('搜索知识库','search','primary')}</div><section class="panel" id="search-results"><div class="row spread"><h2>我的知识与经验</h2>${tag(S.stats.documents+' 份已索引资料')}</div>${S.notes.slice(0,4).map(n=>`<div class="search-result"><h3>${esc(n.title)}</h3><p>${esc(clip(n.body,150))}</p>${btn('回读记录','read:note:'+n.id,'linkbtn')}</div>`).join('')||'<p class="muted">从一个具体词开始。查找到的内容保留来源，原文不会自动发送到模型。</p>'}</section>`;
}else if(page==='process'){v.innerHTML=title('连接与留底','数据、过程与可复用方法，各有自己的去处。')+`<div class="stats"><div class="stat"><b>${S.stats.advisors}</b><small>顾问来源 / ${S.stats.installed} 个本机可读</small></div><div class="stat"><b>${S.stats.methods}</b><small>本项目登记的方法流程</small></div><div class="stat"><b>${S.stats.documents}</b><small>统一索引文档，不等于独立证据数</small></div></div><div class="equal-grid"><section class="panel"><h2>本机连接</h2><p>Codex：${S.connection.codex_available?'本机程序可用':'尚未配置'}</p><p>最近一轮：${statuses[S.connection.last_codex]||'还没有实际发送'}</p><p>知识库：${S.connection.knowledge_connected?'本地索引已连接':'尚未连接，可继续保存本地记录'}</p><small>工作台保留自己的对话历史，不恢复桌面端原聊天。</small></section><section class="panel"><h2>私人内容与公开方法</h2><p>个人资料、目标、想法和对话保存在私人目录。公开包单独审查，不包含这些内容。</p><p>第三方顾问按各自许可处理，公开目录不等于所有正文都可再分发。宣传创作资料保持私有。</p></section></div>`+section('最近操作留底')+'<section class="panel" id="audit-list"></section>';const r=await api('/api/audit');$('#audit-list').innerHTML=r.events.slice(0,30).map(e=>{let d={};try{d=JSON.parse(e.detail)}catch{}return `<div class="timeline">${esc(e.action)} · ${esc(d.kind||'记录')}<small>${time(e.at)} · ${esc(e.object_id?.slice(0,10))} · 版本 ${esc(d.rev)}</small></div>`}).join('')||'<p class="subtle">还没有操作记录。</p>'}
}

function methodSection(){const ms=list(S.methods);if(!ms.length)return '';return `<details class="panel method-section"><summary><strong>方法架 · ${ms.length} 条去重方法</strong><span class="subtle"> 从读懂到运用，选择一条具体路径</span></summary><div class="method-grid">${ms.map(m=>`<button data-action="method:${esc(m.id)}"><strong>${esc(m.title)}</strong><small>${esc(clip(plain(list(m.steps)[0]),55))}</small></button>`).join('')}</div><p class="subtle">这是项目登记的去重方法，不代表所有顾问原文方法的总数。</p></details>`}

function publicPlanNotice(){return '<section class="panel"><h2>把自己的方向，带进这间书房。</h2><p>当前没有接入个人方案。这里不会冒用他人的生活资料。你可以先学习顾问方法、记录困惑，并在「连接与留底」查看本机状态。</p>'+btn('先和顾问讨论','page:chat','primary')+'</section>'}
function advisorDomains(a){return domains().filter(d=>list(d.advisor_slugs).includes(nameOf(a)))}
function advisorTable(){const ds=domain(selectedDomain),filtered=S.advisors.filter(a=>(!advisorCategory||a.category===advisorCategory)&&(!ds||list(ds.advisor_slugs).includes(nameOf(a)))&&(a.title+' '+nameOf(a)+' '+a.category+' '+(a.review_note||'')+' '+advisorDomains(a).map(x=>x.title+' '+x.plan_draft?.title).join(' ')).toLowerCase().includes(advisorQuery.toLowerCase()));return `<table class="library-table"><thead><tr><th>顾问 / 方法</th><th>可以带着什么问题读</th><th>与我的方向</th><th>原文 / 学习</th></tr></thead><tbody>${filtered.map(a=>{const ad=advisorDomains(a),l=S.learning.find(l=>l.advisor===nameOf(a));return `<tr><td><strong>${esc(a.title)}</strong><small>${esc(a.category)}</small></td><td data-label="用途">${esc(clip(a.review_note||ad[0]?.plan_draft?.approach||'从这个顾问的方法，审视一个具体困惑。',100))}</td><td data-label="关联">${ad.length?ad.map(d=>btn(esc(d.title),'domain:'+d.id,'linkbtn')).join(' / '):'<span class="subtle">可以作为补充视角</span>'}</td><td><div class="actions">${btn(a.installed?(l?'继续读 ↗':'阅读 ↗'):'来源 ↗','advisor:'+nameOf(a),'small')}${l?tag(statuses[l.status]||'有记录'):''}</div></td></tr>`}).join('')}</tbody></table>${filtered.length?'':'<div class="empty">没有匹配的顾问，可以清空筛选，或用知识库查一个具体词。</div>'}`}
function continuedReading(){const all=S.learning.slice(0,5);if(!all.length)return '';return section('接着上次，继续读',btn('查看学习记录','learning-history','linkbtn'))+`<div class="continue-list">${all.map(l=>`<article class="continue-card"><small>${statuses[l.status]||'学习记录'} · ${time(l.updated_at||l.read_at)}</small><h3>${esc(advisor(l.advisor)?.title||l.advisor)}</h3><p>${esc(clip(l.insight||'读到这里，接着往下看。',70))}</p>${btn('继续原文 →','resume:'+l.id,'linkbtn')}</article>`).join('')}</div>`}
async function enterAdvisor(slug,fileId){close();const a=advisor(slug);if(!a?.installed){open(`<h2>${esc(a?.title||slug)}</h2><p>本机暂未接入此顾问的正文，来源目录保留原项目与许可信息。</p><p>${link(a?.url,'查看来源项目')}</p>`);return}readerInfo=await api('/api/advisor?name='+encodeURIComponent(slug));readerSlug=slug;const ls=list(readerInfo.learning);const old=ls.find(x=>x.status==='reading')||ls[0];const target=fileId||old?.file_id||readerInfo.files?.[0]?.id||'advisor:'+slug;reading=await api('/api/read?id='+encodeURIComponent(target));page='reading';await draw();restoreReadingPosition()}
function restoreReadingPosition(){const l=S.learning.find(x=>x.advisor===readerSlug&&x.file_id===reading?.id),body=$('.reader-main');const percent=Number(l?.position)||0;window.scrollTo({top:l?.status==='reading'&&percent>0&&body?body.offsetTop+Math.round(Math.max(0,body.offsetHeight-innerHeight*.8)*percent/100):0,behavior:'instant'})}
async function renderReader(){if(!readerInfo||!reading){page='advisors';return draw()}const l=S.learning.find(l=>l.advisor===readerSlug&&l.file_id===reading.id),files=list(readerInfo.files);$('#view').innerHTML=title(readerInfo.title,'原文、个人理解与运用记录放在一起。',btn('← 回到书房','page:advisors','small'))+`<div class="reader-layout"><nav class="reader-nav" aria-label="阅读资料目录"><h3>资料目录 <small>${files.length} 份</small></h3>${files.map(f=>`<button class="${f.id===reading.id?'selected':''}" data-action="reader-file:${esc(f.id)}">${esc(f.title||f.path)}<small>${esc(f.type||'资料')} · ${f.characters||0} 字符</small></button>`).join('')}<p class="subtle">${link(readerInfo.url,'原始项目')}</p></nav><article class="panel reader-main"><h1>${esc(reading.title)}</h1><div class="read-meta">${esc(reading.kind||'方法资料')} · ${esc(reading.source||readerInfo.title)}${reading.truncated?' · 当前内容已截断':''}</div><div class="markdown">${readingMarkdown(reading.text)}</div></article><aside class="reader-side"><section class="panel"><div class="eyebrow">读完之后，留下自己的理解</div><h3>这对我有什么用？</h3><label for="learning-insight">一个启发，或你准备怎样试一试</label><textarea id="learning-insight" placeholder="结合自己的处境，用自己的话说……">${esc(l?.insight||'')}</textarea><label for="learning-goal">关联一个正在推进的目标</label><select id="learning-goal"><option value="">暂不关联</option>${S.goals.map(g=>`<option value="${esc(g.id)}" ${l?.goal_id===g.id?'selected':''}>${esc(g.title)}</option>`).join('')}</select><label for="learning-position">阅读位置 <span id="position-value">${Number(l?.position)||0}%</span></label><input type="range" id="learning-position" min="0" max="100" value="${Number(l?.position)||0}"><div class="actions">${btn('记录当前位置，下次继续','learning-save:reading','primary')}${btn('我读完了，保存理解','learning-save:read')}${btn('已实际运用，记下结果','learning-save:practiced')}</div></section><section class="panel"><h3>把阅读接到生活</h3><p class="subtle">一份原文可以带去讨论；自己的理解也可以成为下一步行动。</p><div class="actions">${btn('带原文与顾问讨论','reader-chat','primary')}${btn('把理解存成笔记','learning-note')}</div></section></aside></div>`}
function readingMarkdown(text){let raw=String(text||''),out='';const fm=raw.match(/^---\s*\n([\s\S]*?)\n---\s*\n/);if(fm){out+='<details class="source-notes"><summary>原文件说明</summary><pre>'+esc(fm[1])+'</pre></details>';raw=raw.slice(fm[0].length)}const lines=raw.split('\n');let visible=[];const flush=()=>{if(visible.length){out+=markdown(visible.join('\n'));visible=[]}};for(let i=0;i<lines.length;i++){const h=lines[i].match(/^(#{1,6})\s+(.+)$/);if(h&&/^(本地接入约束|角色扮演规则)/.test(h[2])){flush();const block=[lines[i]],level=h[1].length;while(i+1<lines.length){const next=lines[i+1].match(/^(#{1,6})\s+/);if(next&&next[1].length<=level)break;block.push(lines[++i])}out+='<details class="source-notes"><summary>'+(/本地/.test(h[2])?'接入说明 / 原文件':'角色使用说明 / 原文件')+'</summary><pre>'+esc(block.join('\n'))+'</pre></details>'}else visible.push(lines[i])}flush();return out}
function noteCard(n){return `<article class="note"><div class="row spread"><h3>${esc(n.title)}</h3>${tag(statuses[n.index_state]||n.index_state,n.index_state==='indexed'?'good':'')}</div><small>${time(n.created_at)} · ${{idea:'想法',learning:'学习理解',review:'成长复盘',conversation:'对话结论'}[n.kind]||'记录'}${n.goal_id?' · '+esc(S.goals.find(g=>g.id===n.goal_id)?.title||'已关联目标'):''}</small><pre>${esc(n.body)}</pre>${n.index_error?`<p class="error">${esc(n.index_error)}</p>`:''}<div class="actions">${btn('编辑','note:'+n.id,'linkbtn')}${btn('形成行动','record:note:'+n.id,'linkbtn')}${btn('带去讨论','note-chat:'+n.id,'linkbtn')}${btn(n.index_state==='indexed'?'更新知识库':'并入知识库','index:'+n.id,'linkbtn')}${btn('版本','versions:'+n.id,'linkbtn')}${btn(n.archived?'恢复':'归档','archive:'+n.id,'linkbtn')}</div></article>`}
function renderReview(v){const g=S.goals.find(g=>g.id===selectedDomain),draft=reviewDraft();v.innerHTML=title('一次复盘，把经历变成下一步。','沿着「主线 → 卡点 → 学什么 → 实际结果 → 下一步」整理，不给生活打分。',btn('返回记录','page:notes','small'))+`<div class="review-layout"><section class="panel"><div class="field"><label for="review-goal">这次围绕哪件事</label><select id="review-goal"><option value="">一次综合复盘</option>${S.goals.map(x=>`<option value="${esc(x.id)}" ${(g?.id||draft.goal_id)===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></div><div class="review-fields">${[['main','现在的主线','近期真正想推进什么，而不是所有事一起做。'],['obstacle','卡在哪里','描述实际遇到的阻碍，不急着评价自己。'],['learn','这次学到了什么','一段原文、一个顾问观点，或亲身得到的认识。'],['result','实际做了什么，结果如何','留下作品、反馈、变化；还没做，也如实写。'],['next','下一步怎样调整','缩小一步、换一个方法，或先补充一个事实。']].map(([k,h,sub],i)=>`<div class="review-field"><span class="review-number">${i+1}</span><div><label for="review-${k}">${h}<span>${sub}</span></label><textarea id="review-${k}" data-review="${k}">${esc(draft[k]||(k==='main'?g?.title||'':''))}</textarea></div></div>`).join('')}</div><div class="actions actions-spaced">${btn('保存这次复盘','save-review','primary')}${btn('保存并形成行动','save-review-action')}${btn('保存并入知识库','save-review-index')}</div></section><section class="panel"><div class="eyebrow">把真实经历带进来</div><h2>最近的行动与理解</h2>${activeGoals().slice(0,3).map(x=>`<div class="week-item"><strong>${esc(x.title)}</strong><p>${esc(list(x.steps).find(s=>s.outcome)?.outcome||list(x.steps).find(s=>!s.done)?.text||x.why)}</p></div>`).join('')}${S.learning.filter(x=>x.insight).slice(0,3).map(l=>`<div class="week-item"><strong>${esc(advisor(l.advisor)?.title||l.advisor)}</strong><p>${esc(l.insight)}</p></div>`).join('')}${!activeGoals().length&&!S.learning.some(x=>x.insight)?'<p class="muted">可以从今天一件真实的小事开始。没有可量化的结果，也可以记下新发现的问题。</p>':''}</section></div>`}
function reviewDraft(){try{return JSON.parse(localStorage.getItem('growth-review-draft')||'{}')}catch{return {}}}
function refsHTML(){return selectedRefs.map(r=>`<div class="context-card"><div class="row spread"><strong>${esc(r.title)}</strong>${tag('本轮已选','blue')}</div><div class="actions">${btn('回读原文','read:'+r.id,'linkbtn')}${btn('移除','remove-ref:'+r.id,'linkbtn')}</div></div>`).join('')||'<p class="subtle">还没选择资料。也可以直接讨论，不必携带个人档案。</p>'}
function candidatesHTML(){return contextWarnings.map(w=>'<div class="notice">'+esc(w)+'</div>').join('')+contextCandidates.map(r=>`<div class="context-card"><strong>${esc(r.title)}</strong><p>${esc(r.reason||r.excerpt||'相关资料')}</p><div class="actions">${btn('回读','read:'+r.id,'linkbtn')}${btn(selectedRefs.some(x=>x.id===r.id)?'已选入':'选入本轮','select-ref:'+r.id,'linkbtn')}</div></div>`).join('')}
function updateContext(){if($('#selected-refs'))$('#selected-refs').innerHTML=refsHTML();if($('#context-results'))$('#context-results').innerHTML=candidatesHTML();if($('#context-count'))$('#context-count').textContent=selectedRefs.length;invalidatePreview()}
function invalidatePreview(){if($('#send-preview'))$('#send-preview').innerHTML='<p class="subtle">内容已变化，发送前请重新预览。</p>'}
async function loadMessages(){if(page!=='chat')return;const r=sessionId?await api('/api/messages?session_id='+encodeURIComponent(sessionId)):{messages:[]};lastMessages=r.messages;const box=$('#messages'),atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.innerHTML=r.messages.map(m=>`<article class="message ${m.role==='user'?'user':'assistant'}"><label>${m.role==='user'?'我':'Codex'} · ${time(m.created_at)}</label><div class="markdown">${markdown(m.text)}</div>${m.role==='assistant'?replyEvidence(m)+`<div class="actions">${btn('保存这条结论','save-message:'+m.id,'linkbtn')}${btn('形成目标或行动 →','record:message:'+m.id,'linkbtn')}</div>`:''}</article>`).join('')||`<div class="chatwelcome"><div class="eyebrow">把真实处境带进来</div><h2>从一个具体困惑，聊到一个可做的下一步。</h2><p>右侧可以查找个人材料与顾问原文。发送前，你能看到这一轮会带上什么。</p>${domains().slice(0,3).map(d=>`<button class="suggestion" data-action="domain-question:${esc(d.id)}">${esc(d.plan_draft?.title||d.title)} <span>↗</span></button>`).join('')}</div>`;if(atBottom)box.scrollTop=box.scrollHeight;const job=S.jobs.find(j=>j.session_id===sessionId);$('#job-state').innerHTML=job?`<div class="jobstate ${['failed','interrupted'].includes(job.status)?'error':''}">${statuses[job.status]||job.status} ${esc(job.error||'')}${['queued','running'].includes(job.status)?btn('停止','cancel:'+job.id,'small'):['failed','interrupted','cancelled'].includes(job.status)?btn('恢复问题重试','retry:'+job.id,'small'):''}</div>`:'';if(job&&['queued','running','cancelling'].includes(job.status))poll=setTimeout(async()=>{try{await refresh(false);await loadMessages()}catch(e){toast(e.message)}},1500)}
function replyEvidence(m){const c=m.reply_context;if(!c)return '<details class="reply-evidence"><summary>当轮依据与发送内容</summary><p class="subtle">这条历史回复没有保存可回读的发送快照，不用当前资料替代历史依据。</p></details>';return `<details class="reply-evidence"><summary>当轮依据与发送内容 · ${list(c.contexts).length} 份资料</summary><p class="subtle">这是当时实际发送的快照。右侧资料属于下一轮选择，修改后不会改变此处留底。</p>${c.message?'<div class="context-card"><strong>当轮问题</strong><pre>'+esc(c.message)+'</pre></div>':''}<p class="subtle">当轮携带 ${Number(c.history_count)||0} 条历史</p>${list(c.contexts).map(r=>`<details><summary>${esc(r.title)} · ${esc(r.kind||'资料')}${r.truncated?' · 截取内容':''}</summary><pre class="reading">${esc(r.text)}</pre><small>实际包含 ${Number(r.included_characters)||String(r.text||'').length} 字符</small></details>`).join('')}${list(c.history).length?`<details><summary>当轮历史正文</summary><pre class="reading">${esc(c.history.map(x=>x.role+'：'+x.text).join('\n\n'))}</pre></details>`:''}<details><summary>快照标识</summary><small>预览 ${esc(c.preview_id||'')}<br>内容校验 ${esc(c.context_hash||'')}</small></details></details>`}
function domainDetail(d){open(`<div class="eyebrow">${esc(d.title)} · 从资料整理的方案</div><h2>${esc(d.plan_draft?.title||d.title)}</h2><p>${esc(d.plan_draft?.why||d.priority_reason)}</p><div class="muted-box">${esc(plain(d.plan_draft?.approach)||d.priority_reason)}</div><h3 class="subsection-title">这些判断，来自你的材料</h3>${list(d.known_facts).map(f=>`<div class="evidence-item"><p>${esc(f.text)}</p><small>${esc(f.date||'日期见原文')} · ${esc(f.evidence_type||'材料记录')} · ${esc(f.locator||'')}</small><div>${btn('回读：'+esc(sourceTitle(f.source_id)),'read:source:'+String(f.source_id||'').replace(/^source:/,''),'linkbtn')}</div></div>`).join('')}${list(d.constraints).length?`<h3>需要一起考虑的现实条件</h3><ul>${list(d.constraints).map(x=>'<li>'+esc(plain(x))+'</li>').join('')}</ul>`:''}${list(d.unknowns).length?`<details><summary>还需要补充 ${list(d.unknowns).length} 项信息</summary><ul>${list(d.unknowns).map(x=>'<li>'+esc(plain(x))+'</li>').join('')}</ul></details>`:''}<h3>可选的起步行动</h3>${list(d.actions).map(a=>`<div class="week-item"><strong>${esc(a.title)}</strong><p>${list(a.steps).map(plain).map(esc).join(' → ')}</p><small>完成依据：${esc(plain(a.completion_evidence)||'留下实际结果')}</small></div>`).join('')}<p class="subtle">回看时机：${esc(d.plan_draft?.review_trigger||'行动完成，或现实条件改变时')}</p><div class="actions">${btn('采用并调整这套方案','adopt:'+d.id,'primary')}${btn('先和顾问讨论','domain-chat:'+d.id)}${btn('回读完整方案','read:plan:'+d.id,'linkbtn')}</div>`,true)}
function adoptionForm(d,onlyActionId){adoptDomain=d;const old=activeGoals().find(g=>g.domain_id===d.id);if(old){goalForm(old);return}const steps=list(d.actions).map(a=>({text:a.title,criterion:plain(a.completion_evidence)||'',due:a.due||''}));open(`<div class="eyebrow">${esc(d.title)} · 由你决定开始</div><h2>把整理好的方案，变成自己的计划。</h2><p class="subtle">内容已按你的材料填写。采用后保存为工作台执行目标；原目标台账保持只读，采用状态不会自动写回。</p><div class="field"><label for="adopt-title">这个阶段要做到什么</label><input id="adopt-title" value="${esc(d.plan_draft?.title||d.title)}"></div><div class="field"><label for="adopt-why">为什么值得做</label><textarea id="adopt-why">${esc(d.plan_draft?.why||d.priority_reason)}</textarea></div><div class="formrow"><div class="field"><label for="adopt-priority">当前优先级</label><select id="adopt-priority"><option value="1">优先推进</option><option value="2" selected>稳步推进</option><option value="3">有余力时推进</option></select></div><div class="field"><label for="adopt-due">阶段回看日期（可留空）</label><input type="date" id="adopt-due"></div></div><h3>起步行动，可以删减</h3><div id="adopt-actions">${steps.map((s,i)=>`<div class="evidence-item"><label class="step"><input type="checkbox" data-adopt-check="${i}" ${!onlyActionId||list(d.actions)[i]?.id===onlyActionId?'checked':''}>采用这一步</label><input data-adopt-text="${i}" aria-label="行动 ${i+1}" value="${esc(s.text)}"><div class="field"><label>怎样算做到</label><input data-adopt-criterion="${i}" value="${esc(s.criterion)}"></div><label class="subtle">准备在哪天做</label><input type="date" data-adopt-due="${i}" value="${esc(s.due)}"></div>`).join('')}</div><div class="actions">${btn('确认采用，加入我的计划','save-adopt','primary')}${btn('暂时不采用','close','quiet')}</div>`,true)}
function editedSteps(lines,oldSteps){
 const used=new Set(),matches=lines.map(text=>{const found=oldSteps.find(x=>x.text===text&&!used.has(x.id));if(found)used.add(found.id);return found});
 return lines.map((text,i)=>{if(matches[i])return {...matches[i],text};const prior=oldSteps[i];if(prior&&!used.has(prior.id)){used.add(prior.id);return {...prior,text}}return {text,done:false}});
}
function goalForm(g){g=g||{status:'draft',steps:[],title:'',why:'',due:'',domain:'个人目标'};open(`<div class="eyebrow">目标与计划</div><h2>${g.id?'调整目标，保留过程':'自定一个当前目标'}</h2><div class="field"><label for="g-title">我想实现什么</label><input id="g-title" value="${esc(g.title)}"></div><div class="field"><label for="g-why">为什么值得做</label><textarea id="g-why">${esc(g.why)}</textarea></div><div class="formrow"><div class="field"><label for="g-domain">所属方向</label><select id="g-domain"><option value="">个人自定</option>${domains().map(d=>`<option value="${esc(d.id)}" ${g.domain_id===d.id?'selected':''}>${esc(d.title)}</option>`).join('')}</select></div><div class="field"><label for="g-due">目标日期</label><input type="date" id="g-due" value="${esc(g.due||'')}"></div></div><div class="formrow"><div class="field"><label for="g-status">当前状态</label><select id="g-status">${['draft','active','paused','done','archived'].map(s=>`<option value="${s}" ${g.status===s?'selected':''}>${statuses[s]}</option>`).join('')}</select></div><div class="field"><label for="g-priority">当前优先级</label><select id="g-priority">${[[1,'优先推进'],[2,'稳步推进'],[3,'有余力时推进']].map(([v,t])=>`<option value="${v}" ${(g.priority||2)===v?'selected':''}>${t}</option>`).join('')}</select></div></div><div class="field"><label for="g-parent">连接一个长期目标</label><select id="g-parent"><option value="">独立方向</option>${S.goals.filter(x=>x.id!==g.id).map(x=>`<option value="${esc(x.id)}" ${g.parent_id===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></div><div class="field"><label for="g-steps">接下来做什么（每行一个行动）</label><small>修改原行动标题会保留结果；新增行动请另起一行。</small><textarea id="g-steps">${esc(list(g.steps).map(s=>s.text).join('\n'))}</textarea></div><div class="field"><label for="g-evidence">实际结果与证据（完成目标时填写）</label><textarea id="g-evidence">${esc(g.evidence||'')}</textarea></div>${recordOrigin(g.origin_id)}${g.source_snapshot?'<details><summary>方案来源与采用记录</summary><pre class="reading">'+esc(JSON.stringify(g.source_snapshot,null,2))+'</pre><p class="subtle">保存为工作台执行目标；原目标台账保持只读，采用状态未写回原台账。</p></details>':''}${btn('保存目标','save-goal:'+(g.id||'new'),'primary')}`)}
function noteForm(n){open(`<div class="eyebrow">保留原话，再继续整理</div><h2>${n?.id?'编辑这条记录':'留下一条记录'}</h2><div class="field"><label for="n-title">标题</label><input id="n-title" value="${esc(n?.title||'')}"></div><div class="field"><label for="n-body">内容</label><textarea id="n-body" class="note-editor">${esc(n?.body||'')}</textarea></div><div class="formrow"><div class="field"><label for="n-kind">记录类型</label><select id="n-kind">${[['idea','想法'],['learning','学习理解'],['review','复盘'],['conversation','对话结论']].map(([k,t])=>`<option value="${k}" ${n?.kind===k?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label for="n-goal">关联目标</label><select id="n-goal"><option value="">暂不关联</option>${S.goals.map(g=>`<option value="${esc(g.id)}" ${n?.goal_id===g.id?'selected':''}>${esc(g.title)}</option>`).join('')}</select></div></div><div class="actions">${btn('保存记录','save-note:'+(n?.id||'new'),'primary')}${btn('保存并入知识库','save-index-note:'+(n?.id||'new'))}</div>`)}
function recordDraft(body,title){const text=String(body||'').replace(/\r/g,''),parts=text.split('\n');const next=text.match(/(?:^|\n)#{1,6}\s*(?:下一步|行动计划|行动建议|具体行动|接下来)[^\n]*\n([\s\S]*?)(?=\n#{1,6}\s|$)/);const scope=(next?.[1]||text).split('\n').map(s=>s.trim()).filter(Boolean);const clean=s=>s.replace(/^#{1,6}\s*/,'').replace(/^[-*+]\s+|^\d+[.)、]\s*/,'').replace(/\*\*/g,'').trim();let steps=scope.filter(s=>/^[-*+]\s+|^\d+[.)、]\s*/.test(s)).map(clean);if(!next)steps=steps.filter(s=>/(整理|选择|列出|检查|确认|记录|完成|阅读|练习|写下|回看|核对|尝试|比较|做一次|找出|开始|制定|联系|保存|安排|停止|复盘|检验|收集|更新)/.test(s));if(next&&!steps.length)steps=scope.filter(s=>!/^#/.test(s)).map(clean);steps=steps.filter(s=>s&&s!=='暂未记录').slice(0,5);const first=steps[0]||parts.map(clean).find(s=>s&&s!=='暂未记录')||'';return {title:clip(next?first:title||first,90),why:clip(parts.map(clean).filter(s=>s&&!/^(主线|卡点|学什么|实际结果|下一步)$/.test(s)).join('；'),260),steps}}
function recordForm(sourceId){recordSource=sourceId;const [kind,id]=sourceId.split(':');const src=kind==='message'?lastMessages.find(m=>m.id===id):S.notes.find(n=>n.id===id);const body=src?.text||src?.body||'',draft=recordDraft(body,src?.title);open(`<div class="eyebrow">从讨论与经历，走向行动</div><h2>把值得做的部分，留下来推进。</h2><p class="notice">按原文整理的可编辑草稿，请核对取舍；尚未自动承诺。${draft.steps.length?'':'原文未识别到明确行动，已保留结论，请补充你愿意推进的一步。'}</p><details><summary>回看这条${kind==='message'?'回复':'记录'}</summary><div class="markdown">${markdown(body)}</div></details><div class="field"><label for="record-mode">这次怎样推进</label><select id="record-mode"><option value="goal">形成一个新目标</option>${S.goals.length?'<option value="action">添加到已有目标，作为下一步行动</option>':''}</select></div><div class="field" id="record-existing" hidden><label for="record-goal">关联目标</label><select id="record-goal">${S.goals.map(g=>`<option value="${esc(g.id)}">${esc(g.title)}</option>`).join('')}</select></div><div class="field"><label for="record-title">我愿意推进的这件事</label><input id="record-title" value="${esc(draft.title)}" placeholder="从原文中取舍，用一句话说清楚"></div><div class="field"><label for="record-why">意义 / 完成依据</label><textarea id="record-why" placeholder="怎样才算真的有进展？">${esc(draft.why)}</textarea></div><div id="record-goal-fields"><div class="field"><label for="record-steps">起步行动（每行一个）</label><textarea id="record-steps">${esc(draft.steps.join('\n'))}</textarea></div><div class="field"><label for="record-domain">所属方向</label><select id="record-domain"><option value="">个人自定</option>${domains().map(d=>`<option value="${esc(d.id)}">${esc(d.title)}</option>`).join('')}</select></div></div><div class="formrow"><div class="field"><label for="record-due">准备在哪天做（可留空）</label><input type="date" id="record-due"></div><div class="field"><label for="record-priority">当前优先级</label><select id="record-priority"><option value="1">优先推进</option><option value="2" selected>稳步推进</option><option value="3">有余力时推进</option></select></div></div>${btn('确认，加入我的计划','save-record','primary')}<p class="subtle">这次确认会留下来源关联；不会把整条回复自动当作承诺。</p>`,true)}
async function showRead(id){reading=await api('/api/read?id='+encodeURIComponent(id));open(`<div class="eyebrow">${esc(reading.kind||'原始材料')}</div><h2>${esc(reading.title)}</h2><p class="subtle">${esc(reading.source||'')}${reading.truncated?' · 当前显示内容已截断':''}</p><div class="markdown">${markdown(reading.text)}</div><div class="actions actions-spaced">${btn('选入本轮对话','read-chat','primary')}${btn('关闭','close')}</div>`,true)}
async function requestContext(question){if(!question.trim())throw Error('先说出一个具体问题，我再帮你找资料。');const r=await api('/api/context',{question,domain_id:domain(selectedDomain)?selectedDomain:undefined});contextCandidates=r.candidates||[];contextWarnings=r.warnings||[];if(!contextCandidates.length&&!contextWarnings.length)contextWarnings=['没有找到足够相关的资料。可以换一个具体词，或直接讨论。'];for(const id of r.suggested_ids||[]){const c=contextCandidates.find(x=>x.id===id);if(c&&selectedRefs.length<4)addRef(c)}updateContext();return r}
function draftId(body){let x;try{x=JSON.parse(localStorage.getItem('growth-save-request')||'null')}catch{}if(!x||x.body!==body){x={body,id:crypto.randomUUID()};localStorage.setItem('growth-save-request',JSON.stringify(x))}return x.id}
async function watchIndex(){for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,1500));await refresh(false);if(!S.notes.some(n=>n.index_state==='indexing')){if(page==='notes')await draw();return}}}
async function action(a){const [cmd,...rest]=a.split(':'),id=rest.join(':');
if(cmd==='page')await navigate(id);
else if(cmd==='close')close();
else if(cmd==='quick-note'){noteSeed=null;noteForm(null)}
else if(cmd==='domain')domainDetail(domain(id));
else if(cmd==='filter-domain'){document.querySelectorAll('.filters button').forEach(b=>b.classList.toggle('selected',b.dataset.action==='filter-domain:'+id));$('#domain-grid').innerHTML=(id?[domain(id)]:domains()).filter(Boolean).map(domainCard).join('')}
else if(cmd==='adopt'){const [did,aid]=id.split(':');adoptionForm(domain(did),aid)}
else if(cmd==='save-adopt'){const steps=[...document.querySelectorAll('[data-adopt-check]')].filter(x=>x.checked).map(x=>{const i=x.dataset.adoptCheck,original=list(adoptDomain.actions)[Number(i)];return {plan_action_id:original?.id,canonical_action_ref:original?.canonical_action_ref||'',text:$(`[data-adopt-text="${i}"]`).value,criterion:$(`[data-adopt-criterion="${i}"]`).value,due:$(`[data-adopt-due="${i}"]`).value,done:false}});await api('/api/adopt',{domain_id:adoptDomain.id,title:$('#adopt-title').value,why:$('#adopt-why').value,priority:Number($('#adopt-priority').value),due:$('#adopt-due').value,steps});close();page='goals';await refresh();toast('已采用，接下来按你的节奏推进。')}
else if(cmd==='domain-chat'||cmd==='domain-question'){const d=domain(id);selectedDomain=d.id;localStorage.setItem('growth-chat-draft',`请结合我的资料和顾问方法，帮我讨论「${d.plan_draft?.title||d.title}」。\n${d.plan_draft?.first_question||'先识别当前最关键的卡点，再一起取舍一个能验证的下一步。'}`);close();page='chat';await draw();await requestContext($('#chat-text').value)}
else if(cmd==='panorama-discuss'){const p=S.plan?.life_panorama,m=p?.mastery;if(!m)throw Error('尚未接入近期专精方法');selectedDomain='';selectedRefs=[];sessionId='';for(const sid of [...new Set([...list(m.source_id),...list(list(p.route)[0]?.source_ids)])].filter(Boolean).slice(0,4))addRef({id:'source:'+String(sid).replace(/^source:/,''),title:sourceTitle(sid)});localStorage.setItem('growth-chat-draft',`请按我已有的「${m.title||'让我伟大'}」方法，结合当前材料，复盘近期工作如何更专精。\n${list(m.steps).map((x,i)=>`${i+1}. ${x.title}：${x.description}`).join('\n')}\n请先区分本人意愿、当前事实、历史记录和待验证判断。缺少当前成果证据时写明未知，不复用旧进度或收入数字，不自动替我承诺新的行动。\n${m.boundary||''}`);close();page='chat';await draw()}
else if(cmd==='goal')goalForm(S.goals.find(g=>g.id===id));
else if(cmd==='save-goal'){const old=S.goals.find(g=>g.id===id),lines=$('#g-steps').value.split('\n').map(x=>x.trim()).filter(Boolean),did=$('#g-domain').value;await api('/api/goals',{...old,title:$('#g-title').value,why:$('#g-why').value,parent_id:$('#g-parent').value,domain_id:did,domain:domain(did)?.title||'个人自定',due:$('#g-due').value,status:$('#g-status').value,priority:Number($('#g-priority').value),evidence:$('#g-evidence').value,steps:editedSteps(lines,old?.steps||[])});close();await refresh();toast('目标已保存。')}
else if(cmd==='step'){const [gid,sid]=id.split(':'),s=S.goals.find(g=>g.id===gid).steps.find(s=>s.id===sid);open(`<div class="eyebrow">一个具体行动</div><h2>${esc(s.text)}</h2><div class="field"><label for="step-due">准备在哪天做</label><input type="date" id="step-due" value="${esc(s.due||'')}"></div><div class="field"><label for="step-criterion">怎样算做到了</label><textarea id="step-criterion">${esc(s.criterion||'')}</textarea></div><div class="field"><label for="step-outcome">实际结果或证据</label><textarea id="step-outcome">${esc(s.outcome||'')}</textarea></div><label class="step"><input id="step-done" type="checkbox" ${s.done?'checked':''}>这一步已经完成</label>${btn('保存行动安排','save-step:'+id,'primary')}`)}
else if(cmd==='save-step'){const [gid,sid]=id.split(':'),g=structuredClone(S.goals.find(g=>g.id===gid)),s=g.steps.find(s=>s.id===sid);Object.assign(s,{due:$('#step-due').value,criterion:$('#step-criterion').value,outcome:$('#step-outcome').value,done:$('#step-done').checked});await api('/api/goals',g);close();await refresh();toast('行动和结果已保存。')}
else if(cmd==='discuss-goal'){const g=S.goals.find(g=>g.id===id);selectedDomain=g.domain_id||'';localStorage.setItem('growth-chat-draft',`我想讨论正在推进的目标：${g.title}\n请先帮我找出当前卡点，再讨论下一步。`);close();page='chat';await draw();$('#include-goals').checked=true;await requestContext($('#chat-text').value)}
else if(cmd==='capture-save'||cmd==='capture-index'){const b=$('#capture').value;if(!b.trim())throw Error('先留下一句想法。');await api('/api/notes',{body:b,kind:'idea',index:cmd==='capture-index',request_id:draftId(b)});localStorage.removeItem('growth-draft');localStorage.removeItem('growth-save-request');await refresh();toast(cmd==='capture-index'?'想法已保存，正在并入知识库。':'想法已保存。');if(cmd==='capture-index')watchIndex().catch(e=>toast(e.message))}
else if(cmd==='capture-chat'){localStorage.setItem('growth-chat-draft',$('#capture').value);await navigate('chat')}
else if(cmd==='toggle-archive'){showArchived=!showArchived;await draw()}
else if(cmd==='archive'){const n=S.notes.find(n=>n.id===id);await api('/api/note/archive',{id,archived:!n.archived});await refresh();toast(n.archived?'记录已恢复。':'已归档，原文与版本仍然保留。')}
else if(cmd==='note'){noteSeed=null;noteForm(S.notes.find(n=>n.id===id))}
else if(cmd==='save-note'||cmd==='save-index-note'){const old=S.notes.find(n=>n.id===id);await api('/api/notes',{...old,...(!old?noteSeed||{}:{}),title:$('#n-title').value,body:$('#n-body').value,kind:$('#n-kind').value,goal_id:$('#n-goal').value,index:cmd==='save-index-note',request_id:!old?draftId($('#n-body').value):undefined});close();noteSeed=null;await refresh();toast(cmd==='save-index-note'?'记录已保存，正在入库。':'记录已保存。');if(cmd==='save-index-note')watchIndex().catch(e=>toast(e.message))}
else if(cmd==='index'){await api('/api/index',{id});await refresh();toast('正在并入知识库，完成后更新状态。');watchIndex().catch(e=>toast(e.message))}
else if(cmd==='versions'){const r=await api('/api/versions?id='+encodeURIComponent(id));open('<h2>这条记录的变化</h2>'+r.versions.map(v=>`<details><summary>版本 ${v.rev} · ${time(v.data.updated_at)}</summary><pre class="reading">${esc(v.data.body||JSON.stringify(v.data,null,2))}</pre></details>`).join(''))}
else if(cmd==='note-chat'){const n=S.notes.find(n=>n.id===id);addRef({id:'note:'+id,title:n.title});localStorage.setItem('growth-chat-draft','我想接着这条记录讨论：'+n.title);await navigate('chat')}
else if(cmd==='review'){selectedDomain=id;await navigate('review')}
else if(cmd==='save-review'||cmd==='save-review-action'||cmd==='save-review-index'){const fields=['main','obstacle','learn','result','next'],values=Object.fromEntries(fields.map(k=>[k,$('#review-'+k).value.trim()]));if(!values.main||!values.result)throw Error('请至少写下当前主线和真实结果；尚未行动也可以如实记录。');const body=[['主线',values.main],['卡点',values.obstacle],['学什么',values.learn],['实际结果',values.result],['下一步',values.next]].map(([h,t])=>'## '+h+'\n'+(t||'暂未记录')).join('\n\n');const n=await api('/api/notes',{title:S.date+' · '+clip(values.main,45),body,kind:'review',goal_id:$('#review-goal').value,index:cmd==='save-review-index',request_id:draftId(body)});localStorage.removeItem('growth-review-draft');await refresh(false);if(cmd==='save-review-action'){recordForm('note:'+n.id);$('#record-title').value=values.next||values.main;if($('#record-mode')&&$('#review-goal')?.value){$('#record-mode').value='action';$('#record-goal').value=$('#review-goal').value;toggleRecordMode()}}else{page='notes';await draw()}toast('复盘已保存。');if(cmd==='save-review-index')watchIndex().catch(e=>toast(e.message))}
else if(cmd==='method'){const m=list(S.methods).find(m=>m.id===id);if(m)open(`<div class="eyebrow">本项目登记的方法 · ${esc(m.id)}</div><h2>${esc(m.title)}</h2><div class="markdown"><ol>${list(m.steps).map(t=>'<li>'+esc(plain(t))+'</li>').join('')}</ol></div><h3>留下什么结果</h3><ul>${list(m.outputs).map(t=>'<li>'+esc(plain(t))+'</li>').join('')}</ul><div class="actions">${list(m.advisor_slugs).map(slug=>btn('阅读 '+esc(advisor(slug)?.title||slug),'advisor:'+slug,'small')).join('')}</div><details><summary>方法来源与说明</summary>${list(m.source_urls).map(u=>'<p>'+link(u,'来源原文')+'</p>').join('')}<p class="subtle">${esc(m.license_basis||'')}</p></details>`,true)}
else if(cmd==='library-domain'){selectedDomain=id;advisorQuery='';advisorCategory='';await draw()}
else if(cmd==='library-all'){selectedDomain='';advisorQuery='';advisorCategory='';await draw()}
else if(cmd==='advisor')await enterAdvisor(id);
else if(cmd==='resume'){const l=S.learning.find(l=>l.id===id);await enterAdvisor(l.advisor,l.file_id)}
else if(cmd==='reader-file'){reading=await api('/api/read?id='+encodeURIComponent(id));await renderReader();window.scrollTo({top:0,behavior:'instant'})}
else if(cmd==='learning-save'){const insight=$('#learning-insight').value;if(id==='reading'&&!$('#learning-position').dataset.changed){const body=$('.reader-main'),p=Math.round(Math.max(0,Math.min(1,(window.scrollY-body.offsetTop)/Math.max(1,body.offsetHeight-innerHeight*.8)))*100);$('#learning-position').value=p;$('#position-value').textContent=p+'%'}if(id==='practiced'&&!insight.trim())throw Error('写下实际运用的结果，再记录为已实践。');await api('/api/learning',{advisor:readerSlug,file_id:reading.id,status:id,insight,goal_id:$('#learning-goal').value,position:id==='read'||id==='practiced'?100:Number($('#learning-position').value)});await refresh(false);toast(id==='reading'?'阅读位置和理解已保存，下次可以继续。':id==='read'?'已记录读完；有用的部分，可以继续落成行动。':'实践结果已保存。')}
else if(cmd==='learning-note'){noteSeed={kind:'learning',source:reading.id,title:'关于'+readerInfo.title+'的理解',body:$('#learning-insight').value,goal_id:$('#learning-goal').value};noteForm(noteSeed)}
else if(cmd==='reader-chat'){addRef(reading);const insight=$('#learning-insight')?.value;if(insight)localStorage.setItem('growth-chat-draft',`刚读了「${reading.title}」，我的理解是：\n${insight}\n请帮我结合实际处境，讨论如何运用。`);await navigate('chat')}
else if(cmd==='learning-history'){open('<div class="eyebrow">真实阅读与运用记录</div><h2>我的学习足迹</h2>'+S.learning.map(l=>`<article class="note"><div class="row spread"><h3>${esc(advisor(l.advisor)?.title||l.advisor)}</h3>${tag(statuses[l.status]||l.status)}</div><small>${time(l.updated_at||l.read_at)} · 阅读位置 ${Number(l.position)||0}%</small><p>${esc(l.insight||'还没有写下理解。')}</p>${btn('继续这份原文','resume:'+l.id,'linkbtn')}</article>`).join(''))}
else if(cmd==='read')await showRead(id);
else if(cmd==='read-chat'){addRef(reading);close();if(page!=='chat')await navigate('chat');else updateContext()}
else if(cmd==='select-ref'){const c=contextCandidates.find(r=>r.id===id);if(c)addRef(c);updateContext()}
else if(cmd==='remove-ref'){selectedRefs=selectedRefs.filter(r=>r.id!==id);updateContext()}
else if(cmd==='context-search'){const q=$('#context-query').value.trim();if(!q)throw Error('先输入一个关键词。');const r=await api('/api/search?q='+encodeURIComponent(q));contextCandidates=r.results||[];contextWarnings=contextCandidates.length?[]:['没有匹配这个词，换一个更具体的关键词试试。'];updateContext()}
else if(cmd==='recommend-context'){await requestContext($('#chat-text').value);toast(contextCandidates.length?'相关资料已在右侧列出。你可以回读、移除，再预览发送。':'这次没有找到相关资料，可以换一个词继续查找。')}
else if(cmd==='quote-source'){const q=S.quote;if(!q)return;open(`<div class="eyebrow">每日提醒 · 出处</div><h2>${esc(q.advisor)}</h2>${tag(q.type)}<blockquote>${esc(q.text)}</blockquote><p>${esc(q.original||'原文请查看来源')}</p><p class="subtle">${esc(q.source_locator||'')}</p><p>${link(q.source_url,'查看原始来源')}</p><p class="subtle">行动思考问题由工作台撰写，不是顾问原话。</p>`)}
else if(cmd==='quote-next'){S.quote=await api('/api/quote?offset='+ ++quoteOffset);await draw()}
else if(cmd==='quote-chat'){const q=S.quote;localStorage.setItem('growth-chat-draft',`今天的提醒是「${q.text}」，${q.advisor}，${q.type}。来源：${q.source_url}\n请结合我的处境，帮我把这个提醒变成一个适合今天的小行动。`);await navigate('chat')}
else if(cmd==='new-chat'){sessionId='';selectedRefs=[];contextCandidates=[];contextWarnings=[];await draw()}
else if(cmd==='session'){sessionId=id;await draw()}
else if(cmd==='preview'){const r=await api('/api/chat/preview',{message:$('#chat-text').value,session_id:sessionId||null,refs:selectedRefs.map(r=>r.id),include_goals:$('#include-goals').checked});$('#send-preview').innerHTML=`<div class="context"><div class="eyebrow">本轮发送预览</div><h3>确认这些内容再发送</h3><p>你的问题、${r.history_count} 条历史、${r.contexts.length} 份资料。</p><details open><summary>当前问题</summary><pre>${esc(r.message)}</pre></details><details><summary>携带的历史 · ${r.history_count} 条</summary><pre>${esc(list(r.history).map(h=>h.role+'：'+h.text).join('\n\n'))}</pre></details>${r.contexts.map(c=>`<details><summary>${esc(c.title)} · ${esc(c.kind)}</summary><pre>${esc(c.text)}</pre></details>`).join('')}<div class="actions">${btn('确认发送给 Codex','send:'+r.id,'primary')}${btn('返回修改','dismiss-preview','linkbtn')}</div><small>通过当前 Codex 路由处理。</small></div>`;const ctx=$('.chat-context');ctx.open=true;$('#send-preview').scrollIntoView({behavior:'smooth',block:'nearest'})}
else if(cmd==='dismiss-preview')invalidatePreview();
else if(cmd==='send'){const r=await api('/api/chat/send',{preview_id:id});sessionId=r.session_id;localStorage.removeItem('growth-chat-draft');await refresh();toast('已发送，等待 Codex 的实际回复。')}
else if(cmd==='cancel'){await api('/api/chat/cancel',{id});await refresh()}
else if(cmd==='retry'){const j=S.jobs.find(j=>j.id===id);localStorage.setItem('growth-chat-draft',j.message);await draw();toast('原问题已恢复，重新预览后即可发送。')}
else if(cmd==='save-message'){const m=lastMessages.find(m=>m.id===id);noteSeed={body:m.text,kind:'conversation',source:'codex:'+m.job_id,title:'Codex 讨论结论'};noteForm(noteSeed)}
else if(cmd==='record')recordForm(id);
else if(cmd==='save-record'){const common={source_id:recordSource,due:$('#record-due').value};if($('#record-mode').value==='action'){await api('/api/action-from-record',{...common,goal_id:$('#record-goal').value,text:$('#record-title').value,criterion:$('#record-why').value})}else{const did=$('#record-domain').value;await api('/api/goal-from-record',{...common,title:$('#record-title').value,why:$('#record-why').value,domain_id:did,domain:domain(did)?.title||'个人自定',priority:Number($('#record-priority').value),steps:$('#record-steps').value.split('\n').map(x=>x.trim()).filter(Boolean).map(text=>({text,done:false}))})}close();page='goals';await refresh();toast('已经加入计划，并保留了这条原始记录。')}
else if(cmd==='search'){knowledgeQuery=$('#knowledge-query').value;const r=await api('/api/search?q='+encodeURIComponent(knowledgeQuery));$('#search-results').innerHTML=`<div class="row spread"><h2>查到 ${r.results.length} 条相关内容</h2><small>关键词：${esc(knowledgeQuery)}</small></div>`+r.results.map(x=>`<article class="search-result"><div class="row spread"><h3>${esc(x.title)}</h3>${tag((x.collection||'资料')+' · '+(x.status||'可回读'))}</div><p>${esc(x.excerpt)}</p>${btn('回读原文 →','read:'+x.id,'linkbtn')}</article>`).join('')+(r.results.length?'':'<div class="empty">没有匹配这个词。可以缩短关键词，或换一个更具体的说法。</div>')}
}
function toggleRecordMode(){const isAction=$('#record-mode').value==='action';$('#record-existing').hidden=!isAction;$('#record-goal-fields').hidden=isAction}
document.addEventListener('click',async e=>{const n=e.target.closest('[data-page],[data-action]');if(!n)return;e.preventDefault();try{n.disabled=true;if(n.dataset.page)await navigate(n.dataset.page);else await action(n.dataset.action)}catch(err){toast(err.message)}finally{n.disabled=false}});
document.addEventListener('input',e=>{const id=e.target.id;if(id==='capture')localStorage.setItem('growth-draft',e.target.value);if(id==='chat-text'){localStorage.setItem('growth-chat-draft',e.target.value);invalidatePreview()}if(id==='advisor-search'){advisorQuery=e.target.value;$('#advisor-results').innerHTML=advisorTable()}if(id==='learning-position'){$('#position-value').textContent=e.target.value+'%';e.target.dataset.changed='true'}if(e.target.dataset.review){const d=reviewDraft();d[e.target.dataset.review]=e.target.value;d.goal_id=$('#review-goal').value;localStorage.setItem('growth-review-draft',JSON.stringify(d))}});
document.addEventListener('change',async e=>{try{const id=e.target.id;if(id==='category'){advisorCategory=e.target.value;$('#advisor-results').innerHTML=advisorTable()}if(id==='include-goals')invalidatePreview();if(id==='session-select'){sessionId=e.target.value;await draw()}if(id==='record-mode')toggleRecordMode();if(id==='review-goal'){const d=reviewDraft();d.goal_id=e.target.value;localStorage.setItem('growth-review-draft',JSON.stringify(d))}if(e.target.dataset.step){const [gid,sid]=e.target.dataset.step.split(':'),g=structuredClone(S.goals.find(g=>g.id===gid));g.steps.find(s=>s.id===sid).done=e.target.checked;await api('/api/goals',g);await refresh();toast('行动状态已保存；可以在「安排与结果」补充证据。')}}catch(err){toast(err.message);await refresh()}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&['knowledge-query','context-query'].includes(e.target.id)){e.preventDefault();action(e.target.id==='knowledge-query'?'search':'context-search').catch(err=>toast(err.message))}});
let wasNarrow=window.innerWidth<=760;window.addEventListener('resize',()=>{const narrow=window.innerWidth<=760;if(narrow&&!wasNarrow&&$('.chat-context'))$('.chat-context').open=false;wasNarrow=narrow});
$('#close-modal').onclick=close;
refresh().catch(e=>{$('#view').innerHTML='<section class="panel"><h1>暂时没能读到工作台。</h1><p>请确认本地服务已启动，再刷新页面。浏览器中保存的输入草稿仍然保留。</p></section>';toast(e.message)});
